import { generateID } from './common';

export const FormControlNames = {
	STEPCONTAINER: 'step-container',
	INPUTTEXTFIELD: 'text-field',
	INPUTEMAILFIELD: 'email-field',
	INPUTNUMBERFIELD: 'number-field',
	INPUTMULTILINE: 'multiline-text-field',
	CHECKBOX: 'checkbox',
	RADIOGROUP: 'radio-group',
	SELECTDROPDOWN: 'select-drop-down',
	DATEFIELD: 'date-field',
	TIMEFIELD: 'time-field',
	FILEUPLOAD: 'file-upload',
	IMAGEUPLOAD: 'image-upload',
	TOGGLE: 'toggle',
	CHECKLIST: 'checklist',
	SIGNATURE: 'signature',
	MULTICHOICES: 'multi-choices',
	MULTISELECT: 'multi-select',
	SCANCODE: 'scan-code',
	VERIFIEDID: 'verified-id',
	UNIVERSITYDROPDOWN: 'university-dropdown',
};

export const FormTextDataTypes = {
	TEXT: 'text',
	NUMBER: 'number',
	EMAIL: 'email',
};

export const FormItemTypes = {
	CONTROL: 'control',
	CONTAINER: 'container',
};

export const FormPublishStatus = {
	DRAFT: 'draft',
	PUBLISHED: 'published',
};

export const FormContainerList = [
	{
		id: '',
		controlName: FormControlNames.STEPCONTAINER,
		displayText: 'Workflow Step',
		itemType: FormItemTypes.CONTAINER,
		icon: 'fa fa-building',
		heading: 'Container Heading',
		subHeading: 'Container SubHeading',
	},
];

export const FormControlList = [
	{
		id: '',
		controlName: FormControlNames.INPUTTEXTFIELD,
		displayText: 'Text Field',
		placeholder: 'Placeholder for Text Field',
		description: 'Some Description about the field',
		labelName: 'Text Field',
		itemType: FormItemTypes.CONTROL,
		dataType: FormTextDataTypes.TEXT,
		icon: 'fas fa-text-height',
		required: false,
		category: 'text-elements',
		containerId: '',
	},
	{
		id: '',
		controlName: FormControlNames.INPUTEMAILFIELD,
		displayText: 'Email Field',
		placeholder: 'Placeholder for Email Field',
		description: 'Some Description about the field',
		labelName: 'Email Field',
		itemType: FormItemTypes.CONTROL,
		dataType: FormTextDataTypes.EMAIL,
		icon: 'fa fa-envelope',
		required: false,
		category: 'text-elements',
		containerId: '',
	},
	{
		id: '',
		controlName: FormControlNames.INPUTNUMBERFIELD,
		displayText: 'Number Field',
		placeholder: 'Placeholder for Number Field',
		description: 'Some Description about the field',
		labelName: 'Number Field',
		itemType: FormItemTypes.CONTROL,
		dataType: FormTextDataTypes.NUMBER,
		icon: '	fas fa-sort-numeric-up',
		required: false,
		category: 'number-elements',
		containerId: '',
	},
	{
		id: '',
		controlName: FormControlNames.INPUTMULTILINE,
		displayText: 'Notes',
		description: 'Some Description about the field',
		placeholder: 'Please write your notes here.',
		labelName: 'Notes',
		rows: 4,
		itemType: FormItemTypes.CONTROL,
		icon: 'far fa-file',
		required: false,
		category: 'text-elements',
		containerId: '',
	},
	{
		id: '',
		controlName: FormControlNames.RADIOGROUP,
		displayText: 'Radio',
		description: 'Some Description about the field',
		labelName: 'Label for Radio',
		itemType: FormItemTypes.CONTROL,
		icon: 'far fa-dot-circle',
		required: false,
		items: [
			{
				id: generateID(),
				value: 'Button 1',
				label: 'Button 1',
			},
			{
				id: generateID(),
				value: 'Button 2',
				label: 'Button 2',
			},
		],
		category: 'other-elements',
		containerId: '',
	},
	// {
	//   id: "",
	//   controlName: FormControlNames.TOGGLE,
	//   displayText: "Toggle",
	//   description: "Some Description about the field",
	//   labelName: "Label for Toggle",
	//   itemType: FormItemTypes.CONTROL,
	//   icon: "fas fa-toggle-on",
	//   required: false,
	//   category: "other-elements",
	//   containerId: "",
	// },
	{
		id: '',
		controlName: FormControlNames.CHECKLIST,
		displayText: 'Checklist',
		description: 'Some Description about the field',
		labelName: 'Label for Checklist',
		itemType: FormItemTypes.CONTROL,
		icon: 'fas fa-tasks',
		required: false,
		items: [
			{
				id: generateID(),
				value: 'Check 1',
				label: 'Check 1',
			},
			{
				id: generateID(),
				value: 'Check 2',
				label: 'Check 2',
			},
		],
		category: 'other-elements',
		containerId: '',
	},

	{
		id: '',
		controlName: FormControlNames.SELECTDROPDOWN,
		displayText: 'Dropdown',
		description: 'Some Description about the field',
		labelName: 'Label for Dropdown',
		itemType: FormItemTypes.CONTROL,
		icon: 'far fa-caret-square-down',
		required: false,
		items: [
			{
				id: generateID(),
				value: 'Option 1',
				label: 'Option 1',
			},
			{
				id: generateID(),
				value: 'Option 2',
				label: 'Option 2',
			},
		],
		category: 'other-elements',
		containerId: '',
	},

	{
		id: '',
		controlName: FormControlNames.UNIVERSITYDROPDOWN,
		displayText: 'University Dropdown',
		description: 'Some Description about the field',
		labelName: 'Label for Dropdown',
		itemType: FormItemTypes.CONTROL,
		icon: 'far fa-caret-square-down',
		required: false,
		items: [
			{
				id: generateID(),
				value: 'Jawaharlal Nehru University',
				label: 'Jawaharlal Nehru University',
			},
			{
				id: generateID(),
				value: 'Indian Institute of Technology Bombay',
				label: 'Indian Institute of Technology Bombay',
			},
			{
				id: generateID(),
				value: 'Indian Institute of Technology Delhi',
				label: 'Indian Institute of Technology Delhi',
			},

			{
				id: generateID(),
				value: 'University of Delhi',
				label: 'University of Delhi',
			},
		],
		category: 'other-elements',
		containerId: '',
	},
	{
		id: '',
		controlName: FormControlNames.MULTISELECT,
		displayText: 'Multi Select',
		description: 'Some Description about the field',
		labelName: 'Label for Multi Select',
		itemType: FormItemTypes.CONTROL,
		icon: 'far fa-caret-square-down',
		required: false,
		items: [
			{
				id: generateID(),
				value: 'Option 1',
				label: 'Option 1',
			},
			{
				id: generateID(),
				value: 'Option 2',
				label: 'Option 2',
			},
		],
		category: 'other-elements',
		containerId: '',
	},
	// {
	//   id: "",
	//   controlName: FormControlNames.CHECKBOX,
	//   displayText: "Checkbox",
	//   description: "Some Description about the field",
	//   labelName: "Label for Checkbox",
	//   placeholder: "Place Holder Text",
	//   itemType: FormItemTypes.CONTROL,
	//   icon: "far fa-check-square",
	//   required: false,
	//   category: "other-elements",
	//   containerId: "",
	// },
	{
		id: '',
		controlName: FormControlNames.DATEFIELD,
		displayText: 'Date Picker',
		description: 'Some Description about the field',
		labelName: 'Label for Date',
		itemType: FormItemTypes.CONTROL,
		icon: 'far fa-calendar',
		required: false,
		category: 'date-elements',
		containerId: '',
	},
	{
		id: '',
		controlName: FormControlNames.TIMEFIELD,
		displayText: 'Time',
		description: 'Some Description about the field',
		labelName: 'Label for Time',
		itemType: FormItemTypes.CONTROL,
		icon: 'far fa-clock',
		required: false,
		category: 'date-elements',
		containerId: '',
	},
	// {
	// 	id: '',
	// 	controlName: FormControlNames.SIGNATURE,
	// 	displayText: 'Signature',
	// 	description: 'Some Description about the field',
	// 	labelName: 'Label for Signature',
	// 	itemType: FormItemTypes.CONTROL,
	// 	icon: 'fa fa-signature',
	// 	required: false,
	// 	category: 'other-elements',
	// 	containerId: '',
	// },
	{
		id: '',
		controlName: FormControlNames.FILEUPLOAD,
		displayText: 'Upload',
		description: 'Some Description about the field',
		labelName: 'Label for File Upload',
		itemType: FormItemTypes.CONTROL,
		icon: 'fas fa-cloud-upload-alt',
		required: false,
		category: 'media-elements',
		containerId: '',
	},
	// {
	// 	id: '',
	// 	controlName: FormControlNames.IMAGEUPLOAD,
	// 	displayText: 'Image',
	// 	description: 'Some Description about the field',
	// 	labelName: 'Label for Image Upload',
	// 	itemType: FormItemTypes.CONTROL,
	// 	icon: 'far fa-image',
	// 	required: false,
	// 	category: 'media-elements',
	// 	containerId: '',
	// },
];
