export type BankTransactionListVM = {
    transactionId?: string;
    bankId?: string;
    vendorId?: string | null;
    debtorId?: string | null;
    distributorId?: string | null;
    bankName?: string;
    fromBankName?: string;
    toBankName?: string;
    vendorName?: string;
    distributorName?: string;
    approvalId?: string;
    approvalName?: string;
    approvalReference?: string;
    transactionType?: string;
    amount: number;
    deposit: number;
    withdrawal: number;
    runningBalance: number;
    createdDate?: string;
    createdBy?: string;
    lastModifiedDate?: string;
    lastModifiedBy?: string;
    isPaidToDistributor?: boolean;
    isConfirm?: boolean;
    isPartialAmount?: boolean;
    fromBankId?: string | null;
    toBankId?: string | null;
    fromBankUserEmail?: string | null;
    paidToDistributorBy?: string | null;
    paidToDistributorDate?: string | null;
    assignedBankUserId?: string | null;
    derivedStatus?: string;
};
